### PR TITLE
:bug: Fix for mongoose 4.4.6

### PR DESCRIPTION
**Pull request by Lcfvs**
- Matching based on error codes
- Ignore unrequired chars to avoid problems on typo changes
- valueRegex out, useless to declare each time

### CODE REVIEW

**Comment by matteodelabre** [comment]
Hi! Thank you for your help.
I have not reviewed your code yet, I will try to do that this weekend.
Do the tests pass on your machine? There is a bug in the CI as per #9

**Comment by Lcfvs** [comment]
Hi,

Yeah, the tests are passed, except the "custom validation message" ;)

**Comment by matteodelabre** [comment]
Hello @Lcfvs, I do not experience any problem using Mongoose 4.4.7.
Thus I do not understand why we should add the `E1100(?:0|1)` check that you suggest to add in the regex. I try to keep that regex as lightweight as possible to avoid breaking between Mongoose's versions.  There are some problems with the current regex that are going to be fixed with #14.

**Comment by Lcfvs** [comment]
Hi,
Sorry for the delay... I'm ok with the new RegExp, working fine.

For the error code matching, imho, because your doc is matching E11000 & E11001, it shouldn't trap others, if there were to have later, without a new release.

**Comment by matteodelabre** [comment]
I believe we are already checking for that here:
https://github.com/matteodelabre/mongoose-beautiful-unique-validation/blob/master/index.js#L18

**Comment by Lcfvs** [comment]
Hum, ok, sorry...

**Comment by matteodelabre** [comment]
Thank you anyway. :)

**Comment by Lcfvs** [comment]
Thanks to you, useful tool, even if I think to bypass the mongoose validation to make it based on JSON Schemas

**Pull request closed without merging**
