### PR TITLE
Add Model.update beatify support

### PR DESCRIPTION
**Pull request by markwain**
With this PR we can have beaty errors not only on modelInstance.save but also on Model.update.

### CODE REVIEW

**Comment by matteodelabre** [comment]
Hi @markwain, thank you for your contribution! Would you mind adding some tests to the new feature?

**Comment by markwain** [comment]
Hi, I will try to add them as soon as possible

**Comment by matteodelabre** [comment]
Hello @markwain, I recently published v4.0.0 that introduces some changes in the code base (in particular in the test file). Could you please resolve the conflicts on your PR? Sorry for the inconvenience.

**Comment by matteodelabre** [comment]
This is now supported in 5.0.0 via the new Error middlewares.
Thank you for your contribution anyway! :+1:

**Pull request closed without merging**
