### PR TITLE
Support all mongoose types

### PR DESCRIPTION
**Pull request by matteodelabre**
See #23.

### CODE REVIEW

**Comment by matteodelabre** [comment]
Looks like the MongoError object has a `getOperation()` method that returns an useful object:

    { name: 'test',
      group: 57b455957b16685d27d40422,
      age: 42,
      date: 2016-08-17T12:16:21.680Z,
      blob: 
       Binary {
         _bsontype: 'Binary',
         sub_type: 0,
         position: 3,
         buffer: <Buffer 61 62 63> },
      isVerified: false,
      _id: 57b455967b16685d27d40424,
      list: [ 1, 2, 3 ],
      __v: 0 }

**Comment by matteodelabre** [comment]
This is documented on the `WriteError` constructor, here: https://github.com/mongodb/node-mongodb-native/blob/b18ea8c175481261124b7fbed8b44816b1571a55/lib/bulk/common.js#L246

**Comment by matteodelabre** [comment]
@visageae Does this look okay to you?

**Comment by visageae** [comment]
@matteodelabre Awesome ! And way more robust than the pseudo JSON parsing !
Are you gonna merge this ?

**Comment by matteodelabre** [comment]
Yup! Merging this and publishing it as 4.0.0 as it could break some setups.

**Pull request merged**
