### PR TITLE
Fix for findOneAndUpdate post hook

### PR DESCRIPTION
**Pull request by davebaol**
See mongoose issue https://github.com/Automattic/mongoose/issues/5405
Basically, the doc argument is not available in findOneAndUpdate post hook because MongoDB doesn't give you the document back if findOneAndUpdate() fails.
In this situation you have to extract the collection name from the error message (yes, it's a hacky workaround but I could not come up with a cleaner solution)

### CODE REVIEW

**Comment by davebaol** [comment]
Also fixed access to document paths with depth level > 1
For instance, `value = doc[path]` won't work if path is something like `"a.b.c"`.
You have to use `doc.get(path)`

**Comment by matteodelabre** [comment]
Hello @davebaol, thanks for your contribution! I’m still reviewing your proposed changes. Do you have time to add some tests for the use case?

**Comment by davebaol** [comment]
Sure, just committed a very simple test reproducing the issue. 
But I got conflicts now

**Comment by matteodelabre** [comment]
I think we can avoid extracting the collection name from the error message by using `this.model.collection` in the error hook. It looks more robust. What do you think?

https://github.com/matteodelabre/mongoose-beautiful-unique-validation/blob/master/index.js#L144

**Comment by davebaol** [comment]
From your recent commits looks like you got the collection from the model in case of query middleware.
I like your approach, much cleaner than mine.

**Comment by matteodelabre** [comment]
Okay, so I think it is safe to close this. Thanks for bringing the issue up and for your investigation work! I will publish those changes very soon in a major version.

**Comment by davebaol** [comment]
Thanks 👍

**Comment by davebaol** [comment]
Ok just tested my app using your git master branch as dependency.
Glad to say that it works like a charm. 
Great work!

**Comment by matteodelabre** [comment]
Thanks for testing! I just published v6.0.0 to npm.

**Comment by davebaol** [comment]
Great, 6.0.0 from npm works as expected.
You only missed uploading the release on github 😉

**Comment by matteodelabre** [comment]
Well spotted, thank you!

**Pull request closed without merging**
